-- ============================================================================
-- BTN Compliance AI POC - 01: Customer + Transaction tables with synthetic data
-- ============================================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE BTN_POC;
USE DATABASE BTN_COMPLIANCE_AI_DEMO;

-- ============================================================================
-- USE CASE 1: Customer / PII tables (UU PDP scope)
-- ============================================================================
CREATE OR REPLACE TABLE CUSTOMER_DATA.NASABAH (
    CUSTOMER_ID VARCHAR(20),
    NAMA_LENGKAP VARCHAR(100),
    NIK VARCHAR(16),
    EMAIL VARCHAR(100),
    NO_TELEPON VARCHAR(20),
    ALAMAT VARCHAR(200),
    TANGGAL_LAHIR DATE,
    NAMA_IBU_KANDUNG VARCHAR(100),
    NPWP VARCHAR(20),
    PENDAPATAN_BULANAN NUMBER(15,2),
    STATUS_PERNIKAHAN VARCHAR(20),
    PEKERJAAN VARCHAR(50),
    CABANG VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CUSTOMER_DATA.REKENING (
    REKENING_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    NO_REKENING VARCHAR(20),
    TIPE_REKENING VARCHAR(30),
    SALDO NUMBER(18,2),
    MATA_UANG VARCHAR(5),
    TANGGAL_BUKA DATE,
    STATUS VARCHAR(10),
    CABANG VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CUSTOMER_DATA.KARTU_KREDIT (
    CARD_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    NOMOR_KARTU VARCHAR(19),
    NAMA_DI_KARTU VARCHAR(100),
    TANGGAL_KADALUARSA VARCHAR(7),
    CVV VARCHAR(4),
    CREDIT_LIMIT NUMBER(15,2),
    OUTSTANDING_BALANCE NUMBER(15,2),
    STATUS VARCHAR(10),
    TIPE_KARTU VARCHAR(20),
    CABANG VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CUSTOMER_DATA.LOAN_APPLICATION (
    APPLICATION_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    TIPE_PINJAMAN VARCHAR(30),
    JUMLAH_PINJAMAN NUMBER(18,2),
    TENOR_BULAN NUMBER(5,0),
    SUKU_BUNGA NUMBER(5,2),
    PENDAPATAN_PEMOHON NUMBER(15,2),
    CREDIT_SCORE NUMBER(5,0),
    NAMA_PENJAMIN VARCHAR(100),
    NIK_PENJAMIN VARCHAR(16),
    STATUS_APPROVAL VARCHAR(20),
    CATATAN_INTERNAL VARCHAR(500),
    TANGGAL_PENGAJUAN DATE,
    CABANG VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- USE CASE 2-3: Transaction tables (10K rows each)
-- ============================================================================
CREATE OR REPLACE TABLE TRANSACTION_DATA.TLHIST_TRANSAKSI (
    TRX_ID VARCHAR(20),                  -- TLBID
    TRX_DATE TIMESTAMP_NTZ,
    CIF VARCHAR(20),
    NO_REKENING VARCHAR(25),
    REF_NUMBER VARCHAR(40),
    DEBIT_CREDIT VARCHAR(1),             -- D or C
    AMOUNT NUMBER(20,2),
    CURRENCY VARCHAR(5),
    XRATE NUMBER(15,5),
    IDR_AMOUNT NUMBER(20,2),
    TX_CODE VARCHAR(10),
    TX_LOCATION VARCHAR(50),
    TX_REMARK VARCHAR(200),
    TELLER_ID VARCHAR(20),
    AUTH_BY VARCHAR(20),
    CABANG VARCHAR(50),
    POST_DATE DATE,
    TX_MODE VARCHAR(20),                  -- ATM, MB, IB, TLR
    CHANNEL VARCHAR(20),
    NAMA_PENGIRIM VARCHAR(100),
    NAMA_PENERIMA VARCHAR(100),
    REK_LAWAN VARCHAR(25),
    BANK_LAWAN VARCHAR(50),
    NIK_PENGIRIM VARCHAR(16),
    NPWP_PENGIRIM VARCHAR(20),
    IP_ADDRESS VARCHAR(15),
    DEVICE_ID VARCHAR(50),
    STATUS VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE TRANSACTION_DATA.GOAML_ODM_TRANSAKSI (
    TX_ID VARCHAR(20),
    TX_DATE DATE,
    CIF VARCHAR(20),
    ACC_NO VARCHAR(25),
    REF_NUM VARCHAR(40),
    DC VARCHAR(1),
    ORIG_AMT NUMBER(20,2),
    CCY VARCHAR(5),
    XRATE NUMBER(15,5),
    IDR_AMT NUMBER(20,2),
    TX_CODE VARCHAR(10),
    SRC_DATA VARCHAR(20),
    TX_LOC VARCHAR(50),
    TX_REMARK VARCHAR(300),
    TX_NUM VARCHAR(40),
    CNTRY_CODE VARCHAR(5),
    TELLER VARCHAR(20),
    POST_DATE DATE,
    TX_MODE VARCHAR(10),
    CIF_LAWAN VARCHAR(20),
    ACC_LAWAN VARCHAR(25),
    BANK_LAWAN VARCHAR(80),
    SWIFT_LAWAN VARCHAR(20),
    CNTRY_LAWAN VARCHAR(5),
    NAMA_LAWAN_INDV VARCHAR(100),
    NAMA_LAWAN_CORP VARCHAR(100),
    BIZ_DATE DATE,
    NIK_NASABAH VARCHAR(16),              -- KYC indicator
    NPWP_NASABAH VARCHAR(20),
    ADDR_LAWAN VARCHAR(200),
    TX_STATUS VARCHAR(10),
    CABANG VARCHAR(50),
    ACTIVE NUMBER(1),
    CREATED_BY VARCHAR(30),
    CREATED_DT DATE
);

-- 3rd transaction table: BI-RTGS / SKNBI payments
CREATE OR REPLACE TABLE TRANSACTION_DATA.RTGS_SKNBI_PAYMENT (
    PAYMENT_ID VARCHAR(20),
    PAYMENT_DATE TIMESTAMP_NTZ,
    SETTLEMENT_TYPE VARCHAR(10),          -- RTGS or SKNBI
    AMOUNT NUMBER(20,2),
    CURRENCY VARCHAR(5),
    SENDER_BANK VARCHAR(50),
    SENDER_BANK_CODE VARCHAR(10),
    SENDER_ACC VARCHAR(25),
    SENDER_NAME VARCHAR(100),
    SENDER_NIK VARCHAR(16),
    SENDER_NPWP VARCHAR(20),
    SENDER_ADDR VARCHAR(200),
    BENEFICIARY_BANK VARCHAR(50),
    BENEFICIARY_BANK_CODE VARCHAR(10),
    BENEFICIARY_ACC VARCHAR(25),
    BENEFICIARY_NAME VARCHAR(100),
    BENEFICIARY_NIK VARCHAR(16),
    PURPOSE_CODE VARCHAR(10),
    PURPOSE_DESC VARCHAR(200),
    REMITTANCE_INFO VARCHAR(500),
    REF_NUMBER VARCHAR(40),
    BIC_SENDER VARCHAR(15),
    BIC_BENEFICIARY VARCHAR(15),
    SETTLEMENT_STATUS VARCHAR(20),
    SETTLEMENT_TIME TIMESTAMP_NTZ,
    CABANG VARCHAR(50),
    OPERATOR_ID VARCHAR(20),
    APPROVAL_LEVEL VARCHAR(10),
    KYC_VERIFIED VARCHAR(1),              -- Y/N (intentional violations)
    AML_SCREENING VARCHAR(1),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
